query {
  allMerchants {
    id
    name
    categories {
      id
      name
      services {
        id
        name
        description
        price
        openingTime
        closingTime
        availableDays
        imageUrl
      }
    }
  }
}
