query {
  findMerchant {
    name
    categories {
      id
      name
      description
      services {
        id
        name
        description
        price
        openingTime
        closingTime
        availableDays
        imageUrl
      }
    }
    bookings {
      id
      appointmentDate
      upcoming
      cancelled
      completed
      service {
        id
        name
        imageUrl
      }
      user {
        id
        firstName
        lastName
      }
    }
    services {
      bookingCount
      id
      name
      imageUrl
      description
      price
      openingTime
      closingTime
      availableDays
      category {
        id
        name
      }
    }
  }
}
